[package]
name = "learn_opengl_miniquad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = {version = "1.13.1", features = ["derive"]}
glam = "0.24.0"
image = "0.24.6"
miniquad = "0.3.16"
